parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - simple-import-sort
  - unused-imports
rules:
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  "@typescript-eslint/consistent-type-imports": warn
  unused-imports/no-unused-imports: warn
ignorePatterns:
  - "dist/"
  - "tests/django-client-framework/"
