on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Display runner status
        run: |
          echo "hostname -f: $(hostname -f)"
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"

      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: true
          fetch-depth: 2
          submodules: recursive

      - name: Set up env vars
        run: |
          .github/workflows/set_env
          .github/workflows/set_env -w

      - name: Create Pull Request (Staging)
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "staging"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "staging <- ${BRANCH_NAME}: ${COMMIT_TITLE}"

      - name: Create Pull Request (Release)
        if: env.BRANCH_NAME == 'staging'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "release"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "release <- ${BRANCH_NAME}: ${COMMIT_TITLE}"

      - name: Publish if version has been updated
        if: env.BRANCH_NAME == 'release'
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.YLILARRY_NPM_PASSWD }}
