on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Display runner status
        run: |
          echo "hostname -f: $(hostname -f)"
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"

      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: true
          fetch-depth: 2
          submodules: recursive

      - name: Set up env vars
        run: |
          .github/workflows/set_env

      - name: Create Pull Request (Staging)
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "staging"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "staging <- ${BRANCH_NAME}: ${COMMIT_TITLE}"

      - name: Create Pull Request (Release)
        if: env.BRANCH_NAME == 'staging'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "release"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "release <- ${BRANCH_NAME}: ${COMMIT_TITLE}"

      - name: Publish if version has been updated (set up nodejs)
        uses: actions/setup-node@v1
        if: env.SHOULD_UPLOAD_PACKAGE == 'True'
        with:
          node-version: 10

      - name: Publish if version has been updated (npm install)
        if: env.SHOULD_UPLOAD_PACKAGE == 'True'
        run: npm install

      - name: Publish if version has been updated (npm publish)
        if: env.SHOULD_UPLOAD_PACKAGE == 'True'
        run: |
          npm install -g npm-cli-login
          npm-cli-login
          npm publish
        env:
          NPM_USER: ylilarry
          NPM_PASS: ${{ secrets.YLILARRY_NPM_PASSWD }}
          NPM_EMAIL: ylilarry@gmail.com

      - name: Publish if version has been updated (git tag)
        if: env.SHOULD_UPLOAD_PACKAGE == 'True'
        run: |
          git tag v${PACKAGE_VERSION}
          git push --tag
